import requests

url = "http://localhost:8000/save-vehicles"  # Adjust the URL if necessary

data = {
  "brand": {
    "name": "BMW",
    "id": 10,
    "models": [
      {
        "id": 1,
        "model": "BMW 3 Series",
        "description": "Luxury compact sedan known for its performance and handling.",
        "launchPrice": "$42,000",
        "vehicleType": "Sedan",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Jet Black", "Sophisto Grey"],
        "horsepower": "255-382",
        "torque": "295-369 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$42,000",
        "variants": ["330i", "M340i", "330e"],
        "img": []
      },
      {
        "id": 2,
        "model": "BMW 5 Series",
        "description": "Midsize luxury sedan offering comfort and technology.",
        "launchPrice": "$54,000",
        "vehicleType": "Sedan",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Mineral Grey"],
        "horsepower": "248-617",
        "torque": "258-553 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$54,000",
        "variants": ["530i", "540i", "M550i", "M5"],
        "img": []
      },
      {
        "id": 3,
        "model": "BMW X3",
        "description": "Compact luxury SUV with sporty dynamics.",
        "launchPrice": "$43,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Phantom Black", "Sapphire Metallic"],
        "horsepower": "248-503",
        "torque": "258-479 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$43,000",
        "variants": ["X3 sDrive30i", "X3 xDrive30i", "X3 M40i", "X3 M"],
        "img": []
      },
      {
        "id": 4,
        "model": "BMW X5",
        "description": "Luxury midsize SUV with a spacious interior.",
        "launchPrice": "$60,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5-7",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Sparkling Brown"],
        "horsepower": "335-617",
        "torque": "331-553 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$60,000",
        "variants": ["X5 sDrive40i", "X5 xDrive40i", "X5 M50i", "X5 M"],
        "img": []
      },
      {
        "id": 5,
        "model": "BMW Z4",
        "description": "Roadster with sporty performance and sleek design.",
        "launchPrice": "$50,000",
        "vehicleType": "Convertible",
        "seatingCapacity": "2",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Misano Blue", "Black Sapphire"],
        "horsepower": "255-382",
        "torque": "295-369 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$50,000",
        "variants": ["Z4 sDrive30i", "Z4 M40i"],
        "img": []
      },
      {
        "id": 6,
        "model": "BMW 7 Series",
        "description": "Full-size luxury sedan with top-tier technology and comfort.",
        "launchPrice": "$86,000",
        "vehicleType": "Sedan",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Dravit Grey"],
        "horsepower": "335-621",
        "torque": "331-627 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$86,000",
        "variants": ["740i", "745e", "750i", "M760i"],
        "img": []
      },
      {
        "id": 7,
        "model": "BMW 2 Series",
        "description": "Compact luxury coupe with agile handling.",
        "launchPrice": "$36,000",
        "vehicleType": "Coupe",
        "seatingCapacity": "4",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Jet Black", "Mineral Grey"],
        "horsepower": "228-382",
        "torque": "258-369 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$36,000",
        "variants": ["228i", "M235i"],
        "img": []
      },
      {
        "id": 8,
        "model": "BMW X1",
        "description": "Entry-level luxury SUV with a sporty feel.",
        "launchPrice": "$36,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Mineral White"],
        "horsepower": "228",
        "torque": "258 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$36,000",
        "variants": ["X1 sDrive28i", "X1 xDrive28i"],
        "img": []
      },
      {
        "id": 9,
        "model": "BMW 8 Series",
        "description": "Luxury coupe/convertible with stunning design and performance.",
        "launchPrice": "$85,000",
        "vehicleType": "Coupe/Convertible",
        "seatingCapacity": "4",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Macao Blue"],
        "horsepower": "335-617",
        "torque": "368-553 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$85,000",
        "variants": ["840i", "M850i", "M8"],
        "img": []
      },
      {
        "id": 10,
        "model": "BMW i3",
        "description": "All-electric compact car with innovative design.",
        "launchPrice": "$45,000",
        "vehicleType": "Hatchback",
        "seatingCapacity": "4",
        "engineType": "Electric",
        "colorsAvailable": ["Capparis White", "Fluid Black", "Dark Oak"],
        "horsepower": "170",
        "torque": "184 lb-ft",
        "transmission": "Single-speed",
        "releaseDate": "2021-01-01",
        "startingPrice": "$45,000",
        "variants": ["i3", "i3s"],
        "img": []
      },
      {
        "id": 11,
        "model": "BMW X6",
        "description": "Sporty midsize SUV with a bold design.",
        "launchPrice": "$65,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Phytonic Blue"],
        "horsepower": "335-617",
        "torque": "331-553 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$65,000",
        "variants": ["X6 sDrive40i", "X6 xDrive40i", "X6 M50i", "X6 M"],
        "img": []
      },
      {
        "id": 12,
        "model": "BMW M3",
        "description": "High-performance sports sedan with thrilling dynamics.",
        "launchPrice": "$71,000",
        "vehicleType": "Sedan",
        "seatingCapacity": "5",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Jet Black", "Toronto Red"],
        "horsepower": "473-503",
        "torque": "406-479 lb-ft",
        "transmission": "6-speed manual/8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$71,000",
        "variants": ["M3", "M3 Competition"],
        "img": []
      },
      {
        "id": 13,
        "model": "BMW M4",
        "description": "High-performance coupe with exceptional handling.",
        "launchPrice": "$73,000",
        "vehicleType": "Coupe",
        "seatingCapacity": "4",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Portimao Blue"],
        "horsepower": "473-503",
        "torque": "406-479 lb-ft",
        "transmission": "6-speed manual/8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$73,000",
        "variants": ["M4", "M4 Competition"],
        "img": []
      },
      {
        "id": 14,
        "model": "BMW iX",
        "description": "All-electric SUV with cutting-edge technology.",
        "launchPrice": "$84,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5",
        "engineType": "Electric",
        "colorsAvailable": ["Alpine White", "Phytonic Blue", "Black Sapphire"],
        "horsepower": "322-516",
        "torque": "369-749 lb-ft",
        "transmission": "Single-speed",
        "releaseDate": "2021-01-01",
        "startingPrice": "$84,000",
        "variants": ["iX xDrive40", "iX xDrive50"],
        "img": []
      },
      {
        "id": 15,
        "model": "BMW 4 Series",
        "description": "Luxury coupe/convertible with sporty design.",
        "launchPrice": "$48,000",
        "vehicleType": "Coupe/Convertible",
        "seatingCapacity": "4",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Portimao Blue"],
        "horsepower": "255-503",
        "torque": "294-479 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$48,000",
        "variants": ["430i", "M440i", "M4"],
        "img": []
      },
      {
        "id": 16,
        "model": "BMW X2",
        "description": "Compact luxury SUV with a sporty design.",
        "launchPrice": "$38,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Mineral Grey"],
        "horsepower": "228",
        "torque": "258 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$38,000",
        "variants": ["X2 sDrive28i", "X2 xDrive28i"],
        "img": []
      },
      {
        "id": 17,
        "model": "BMW 1 Series",
        "description": "Compact luxury hatchback with sporty handling.",
        "launchPrice": "$35,000",
        "vehicleType": "Hatchback",
        "seatingCapacity": "5",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Seaside Blue"],
        "horsepower": "138-302",
        "torque": "162-332 lb-ft",
        "transmission": "7-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$35,000",
        "variants": ["118i", "120i", "M135i"],
        "img": []
      },
      {
        "id": 18,
        "model": "BMW X4",
        "description": "Sporty midsize SUV with coupe-like styling.",
        "launchPrice": "$52,000",
        "vehicleType": "SUV",
        "seatingCapacity": "5",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Sapphire Metallic"],
        "horsepower": "248-503",
        "torque": "258-479 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$52,000",
        "variants": ["X4 sDrive30i", "X4 xDrive30i", "X4 M40i", "X4 M"],
        "img": []
      },
      {
        "id": 19,
        "model": "BMW M2",
        "description": "Compact high-performance coupe with thrilling dynamics.",
        "launchPrice": "$59,000",
        "vehicleType": "Coupe",
        "seatingCapacity": "4",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Thunder Grey"],
        "horsepower": "453",
        "torque": "406 lb-ft",
        "transmission": "6-speed manual/8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$59,000",
        "variants": ["M2 Competition"],
        "img": []
      },
      {
        "id": 20,
        "model": "BMW M5 Competition",
        "description": "High-performance luxury sedan with exceptional power.",
        "launchPrice": "$113,000",
        "vehicleType": "Sedan",
        "seatingCapacity": "5",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Matte Black"],
        "horsepower": "617",
        "torque": "553 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$113,000",
        "variants": [],
        "img": []
      },
      {
        "id": 21,
        "model": "BMW 6 Series",
        "description": "Luxury coupe with elegant styling and performance.",
        "launchPrice": "$69,000",
        "vehicleType": "Coupe",
        "seatingCapacity": "4",
        "engineType": "Gasoline",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Melbourne Red"],
        "horsepower": "335-640",
        "torque": "332-627 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$69,000",
        "variants": ["640i", "650i", "M6"],
        "img": []
      },
      {
        "id": 22,
        "model": "BMW i4",
        "description": "All-electric gran coupe with sporty performance.",
        "launchPrice": "$56,000",
        "vehicleType": "Gran Coupe",
        "seatingCapacity": "5",
        "engineType": "Electric",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "San Remo Green"],
        "horsepower": "335-536",
        "torque": "317-586 lb-ft",
        "transmission": "Single-speed",
        "releaseDate": "2021-01-01",
        "startingPrice": "$56,000",
        "variants": ["i4 eDrive40", "i4 M50"],
        "img": []
      },
      {
        "id": 23,
        "model": "BMW X7",
        "description": "Full-size luxury SUV with three rows of seating.",
        "launchPrice": "$75,000",
        "vehicleType": "SUV",
        "seatingCapacity": "7",
        "engineType": "Gasoline/Diesel",
        "colorsAvailable": ["Alpine White", "Black Sapphire", "Arctic Grey"],
        "horsepower": "335-612",
        "torque": "331-627 lb-ft",
        "transmission": "8-speed automatic",
        "releaseDate": "2021-01-01",
        "startingPrice": "$75,000",
        "variants": ["X7 xDrive40i", "X7 xDrive50i", "X7 M50i", "X7 M"],
        "img": []
      },
    ]
  }
}





response = requests.post(url, json=data)

print(response.json())







